export const enum MAIN_STATE {
    WAIT = 'WAIT',
    LOADING = 'LOADING',
    LOGIN = 'LOGIN',
    SELECT_SERVER = 'SELECT_SERVER',
    SELECTED_SERVER = 'SELECTED_SERVER',
    START_GAME = 'START_GAME',
}